import React from 'react';
import { StaffMember } from '../../types';
import {
  Users,
  Calendar,
  Clock,
  CheckCircle2,
  XCircle,
  Star,
  IndianRupee,
  TrendingUp,
  Award,
  ShieldCheck,
  Zap,
  BarChart3,
  PieChart as PieIcon,
  Flame,
  UserCheck
} from 'lucide-react';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  PieChart,
  Pie,
  Cell,
  AreaChart,
  Area,
  LineChart,
  Line,
} from 'recharts';

interface StaffDashboardProps {
  staff: StaffMember[];
  onNavigateSubTab?: (tab: 'table' | 'cards') => void;
}

export const StaffDashboard: React.FC<StaffDashboardProps> = ({
  staff,
  onNavigateSubTab,
}) => {
  // Aggregate Calculations
  const totalStaffCount = staff.length;
  const presentCount = staff.filter((s) => s.status === 'Present' || s.status === 'On Shift').length;
  const absentCount = staff.filter((s) => s.status === 'Absent').length;
  const attendanceRate = totalStaffCount > 0 ? Math.round((presentCount / totalStaffCount) * 100) : 0;
  
  const avgStaffRating = totalStaffCount > 0
    ? (staff.reduce((sum, s) => sum + s.customerRating, 0) / totalStaffCount).toFixed(1)
    : '4.8';

  const totalGeneratedSales = staff.reduce((sum, s) => sum + (s.dailySales || (s as any).todaySalesGenerated || 0), 0);

  // Attendance Status Distribution for Pie Chart
  const statusMix = [
    { name: 'On Shift / Active', value: Math.max(1, presentCount), color: '#10b981' },
    { name: 'Scheduled Off / Leave', value: Math.max(1, totalStaffCount - presentCount - absentCount), color: '#6366f1' },
    { name: 'Unscheduled Absent', value: Math.max(1, absentCount), color: '#ef4444' },
  ];

  // Sales per Staff Member comparison
  const staffSalesPerformance = staff.slice(0, 6).map((s) => ({
    name: s.name.split(' ')[0],
    role: s.role,
    salesK: Math.round(((s.dailySales || (s as any).todaySalesGenerated || 16000)) / 1000),
    rating: s.customerRating || 4.8,
    hours: (s as any).hoursWorked || 8,
  }));

  // Hourly Labor Productivity vs Customer Footfall
  const laborProductivityCurve = [
    { hour: '09:00', staffOnFloor: 12, salesVelocityK: 12.4, efficiencyIndex: 94 },
    { hour: '11:00', staffOnFloor: 18, salesVelocityK: 28.6, efficiencyIndex: 96 },
    { hour: '13:00', staffOnFloor: 32, salesVelocityK: 64.2, efficiencyIndex: 99 },
    { hour: '15:00', staffOnFloor: 20, salesVelocityK: 32.0, efficiencyIndex: 95 },
    { hour: '17:00', staffOnFloor: 18, salesVelocityK: 24.8, efficiencyIndex: 93 },
    { hour: '19:00', staffOnFloor: 34, salesVelocityK: 78.9, efficiencyIndex: 98 },
    { hour: '21:00', staffOnFloor: 36, salesVelocityK: 86.4, efficiencyIndex: 99 },
    { hour: '23:00', staffOnFloor: 16, salesVelocityK: 21.5, efficiencyIndex: 92 },
  ];

  return (
    <div id="staff-dashboard" className="space-y-6 pb-6">
      {/* 1. PRIMARY CHARTS: SALES GENERATION PER STAFF & ATTENDANCE MIX */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Top Performer Sales Bar Chart */}
        <div className="lg:col-span-2 bg-white p-6 rounded-3xl border border-slate-200 shadow-xs space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 pb-3">
            <div>
              <h3 className="text-base font-black text-slate-900 flex items-center gap-2">
                <Users className="w-5 h-5 text-indigo-600" />
                <span>Today's Sales Value Generated by Staff (₹ in Thousands)</span>
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Front-of-house order taking and upsell contribution across team members
              </p>
            </div>
            <span className="text-xs font-bold text-indigo-700 bg-indigo-50 px-3 py-1 rounded-full border border-indigo-200">
              Fleet Total: ₹{(totalGeneratedSales / 1000).toFixed(1)}k
            </span>
          </div>

          <div className="h-72 w-full pt-2">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={staffSalesPerformance} margin={{ top: 10, right: 10, left: -15, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: '#64748b' }} />
                <YAxis tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: '#64748b' }} />
                <Tooltip
                  formatter={(val: any) => [`₹${val}k`, 'Sales Generated']}
                  contentStyle={{
                    backgroundColor: '#0f172a',
                    border: 'none',
                    borderRadius: '12px',
                    color: '#fff',
                    fontSize: '12px',
                  }}
                />
                <Bar dataKey="salesK" fill="#6366f1" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          <div className="grid grid-cols-3 gap-3 pt-2 border-t border-slate-100 text-center text-xs">
            <div className="p-2.5 bg-slate-50 rounded-xl">
              <span className="text-[10px] text-slate-400 font-bold uppercase">Shift Attendance Rate</span>
              <p className="text-sm font-black text-emerald-600 mt-0.5">{attendanceRate}% Present</p>
            </div>
            <div className="p-2.5 bg-slate-50 rounded-xl">
              <span className="text-[10px] text-slate-400 font-bold uppercase">Avg Customer CSAT</span>
              <p className="text-sm font-black text-amber-500 mt-0.5 flex items-center justify-center gap-1">
                <Star className="w-3.5 h-3.5 fill-amber-500 text-amber-500" />
                {avgStaffRating} / 5.0
              </p>
            </div>
            <div className="p-2.5 bg-slate-50 rounded-xl">
              <span className="text-[10px] text-slate-400 font-bold uppercase">Active on Duty</span>
              <p className="text-sm font-black text-indigo-600 mt-0.5">{presentCount} Staff Members</p>
            </div>
          </div>
        </div>

        {/* Staff Attendance & Shift Roster Status */}
        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-xs flex flex-col justify-between space-y-4">
          <div className="border-b border-slate-100 pb-3">
            <h3 className="text-base font-black text-slate-900 flex items-center gap-2">
              <PieIcon className="w-5 h-5 text-emerald-600" />
              <span>Shift Attendance Breakdown</span>
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Current roster fulfillment status
            </p>
          </div>

          <div className="h-52 relative flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={statusMix}
                  cx="50%"
                  cy="50%"
                  innerRadius={55}
                  outerRadius={75}
                  paddingAngle={4}
                  dataKey="value"
                >
                  {statusMix.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip
                  formatter={(val: any, name: any) => [`${val} staff members`, name]}
                  contentStyle={{
                    backgroundColor: '#0f172a',
                    border: 'none',
                    borderRadius: '12px',
                    color: '#fff',
                    fontSize: '12px',
                  }}
                />
              </PieChart>
            </ResponsiveContainer>
            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
              <span className="text-2xl font-black text-slate-900">{totalStaffCount}</span>
              <span className="text-[10px] text-slate-400 uppercase font-bold">Total Staff</span>
            </div>
          </div>

          <div className="space-y-1.5 pt-2 border-t border-slate-100">
            {statusMix.map((item) => (
              <div key={item.name} className="flex items-center justify-between text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: item.color }} />
                  <span className="text-slate-600 font-medium">{item.name}</span>
                </div>
                <span className="font-bold text-slate-800">{item.value}</span>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* 2. SECOND ROW: LABOR EFFICIENCY & ON-FLOOR CAPACITY CURVE */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Intraday Labor Floor Allocation Curve */}
        <div className="lg:col-span-2 bg-white p-6 rounded-3xl border border-slate-200 shadow-xs space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <h3 className="text-base font-black text-slate-900 flex items-center gap-2">
                <Clock className="w-5 h-5 text-indigo-600" />
                <span>Intraday Staff Capacity vs Sales Velocity (₹k)</span>
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Staffing levels dynamically scaled to meet lunch and dinner rush demand
              </p>
            </div>
            <span className="px-2.5 py-1 bg-slate-100 text-slate-700 text-xs font-bold rounded-lg">
              Optimal Staff Utilization
            </span>
          </div>

          <div className="h-60 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={laborProductivityCurve} margin={{ top: 10, right: 10, left: -15, bottom: 0 }}>
                <defs>
                  <linearGradient id="staffGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6366f1" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#6366f1" stopOpacity={0.0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="hour" tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: '#64748b' }} />
                <YAxis tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: '#64748b' }} />
                <Tooltip
                  formatter={(val: any, name: string) => [
                    name === 'staffOnFloor' ? `${val} workers on floor` : `₹${val}k sales`,
                    name === 'staffOnFloor' ? 'Floor Coverage' : 'Sales Rate',
                  ]}
                  contentStyle={{
                    backgroundColor: '#0f172a',
                    border: 'none',
                    borderRadius: '12px',
                    color: '#fff',
                    fontSize: '12px',
                  }}
                />
                <Area type="monotone" dataKey="staffOnFloor" stroke="#6366f1" strokeWidth={2.5} fill="url(#staffGrad)" name="staffOnFloor" />
                <Line type="monotone" dataKey="salesVelocityK" stroke="#10b981" strokeWidth={2} dot={{ r: 3 }} name="salesVelocityK" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Roles & Skill Certifications Benchmark */}
        <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-xs space-y-4">
          <div className="border-b border-slate-100 pb-3">
            <h3 className="text-base font-black text-slate-900 flex items-center gap-2">
              <Award className="w-5 h-5 text-amber-500" />
              <span>Skill & Station Certification</span>
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">Kitchen & POS mastery readiness</p>
          </div>

          <div className="space-y-3 pt-1">
            <div className="p-3 bg-slate-50 rounded-2xl border border-slate-100 space-y-1">
              <div className="flex items-center justify-between text-xs">
                <strong className="text-slate-900">Food Safety & Hygiene (FSSAI)</strong>
                <span className="text-emerald-700 font-bold">100% Certified</span>
              </div>
              <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
                <div className="h-full bg-emerald-500 rounded-full" style={{ width: '100%' }} />
              </div>
            </div>

            <div className="p-3 bg-slate-50 rounded-2xl border border-slate-100 space-y-1">
              <div className="flex items-center justify-between text-xs">
                <strong className="text-slate-900">POS & Up-sell Training</strong>
                <span className="text-indigo-700 font-bold">92% Qualified</span>
              </div>
              <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
                <div className="h-full bg-indigo-500 rounded-full" style={{ width: '92%' }} />
              </div>
            </div>

            <div className="p-3 bg-slate-50 rounded-2xl border border-slate-100 space-y-1">
              <div className="flex items-center justify-between text-xs">
                <strong className="text-slate-900">Kitchen Line & Speed SLA</strong>
                <span className="text-amber-700 font-bold">88% Qualified</span>
              </div>
              <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
                <div className="h-full bg-amber-500 rounded-full" style={{ width: '88%' }} />
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
